# Generated by Django 5.2.4 on 2025-08-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="originals/")),
                (
                    "converted_images",
                    models.ImageField(blank=True, null=True, upload_to="converted/"),
                ),
                ("format_form", models.CharField(max_length=10)),
                ("format_to", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
